name: flutter_clean_common_value_objects
description: Common value objects for the domain layer of Clean Architecture
version: 0.1.1
publish_to: none

environment:
  sdk: '>=2.16.0-134.1.beta <3.0.0'

dependencies:
  flutter_clean_domain:
    git:
      url: git@github.com:fabriziocacicia/flutter_clean_domain.git
      ref: v1.2.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_clean_domain_test:
    git:
      url: git@github.com:fabriziocacicia/flutter_clean_domain_test.git
      ref: v1.5.1

  test: ^1.20.2

  # Linting and Code analysis
  dart_lint_rules:
    git:
      url: git@github.com:fabriziocacicia/dart_lint_rules.git
      ref: v0.0.2