name: flutter_clean_common_value_objects
description: Common value objects for the domain layer of Clean Architecture
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  
dependencies:
  flutter_clean_domain:
    git:
      url: git@github.com:fabriziocacicia/flutter_clean_domain.git
      ref: v1.2.0

dev_dependencies:
  # Linting and Code analysis
  dart_lint_rules:
    git:
      url: git@github.com:fabriziocacicia/dart_lint_rules.git
      ref: v0.2.0

  # Testing
  test: ^1.22.0
  flutter_clean_domain_test:
    git:
      url: git@github.com:fabriziocacicia/flutter_clean_domain_test.git
      ref: v1.4.1