name: flutter_clean_common_value_objects
description: Common value objects for the domain layer of Clean Architecure
version: 0.0.1

environment:
  sdk: '>=2.16.0-134.1.beta <3.0.0'


# dependencies:

#dev_dependencies:

