name: flutter_clean_common_value_objects
description: Common value objects for the domain layer of Clean Architecture
version: 0.0.1

environment:
  sdk: '>=2.16.0-134.1.beta <3.0.0'

dependencies:
  flutter_clean_domain:
    git:
      url: git@github.com:fabriziocacicia/flutter_clean_domain.git
      ref: v1.2.0

dev_dependencies:
  flutter_clean_domain_test:
    git:
      url: git@github.com:fabriziocacicia/flutter_clean_domain_test.git
      ref: v1.4.1

